lurk-lab/lurk

Cargo.lock
src/lurk/cli/meta.rs

`!(help hide)`, for example, was failing because `hide` is tagged with `Tag::Builtin` and the logic for `hide` only accepted `Tag::Sym`.
This fix includes `Tag::Builtin` in the condition for the `help` logic.

fix: `help` command

---

src/lurk/eval_tests.rs
src/lurk/parser/syntax.rs
src/lurk/syntax.rs
src/lurk/zstore.rs

Works pretty much identically to bignum syntax with a different prefix. We can bikeshed the actual syntax later, this is for unblocking the micro-chain simulator work.

feat: Add explicit syntax for commitments

---

src/lurk/tag.rs
src/lurk/zstore.rs

* Move `Tag` roundtrip test to `tag.rs`
* Add a test for digest equivalence between symbols and keywords

chore: improve tests

---

src/loam/allocation.rs
src/loam/distilled_evaluation.rs
src/loam/evaluation.rs
src/loam/memory.rs
src/loam/mod.rs
src/lurk/eval_tests.rs
src/lurk/zstore.rs

In this PR:
- Removed `Tag::Nil`
- We preallocate `nil` and `t` to addresses 0 and 1 of `sym_digest_mem`, respectively.
- Shadow tests fail, but commented out for now.

chore: Make sure loam compile on `issue-213`

---

src/lair/air.rs
src/lair/bytecode.rs
src/lair/execute.rs
src/lair/expr.rs
src/lair/macros.rs
src/lair/toplevel.rs
src/lair/trace.rs
src/lurk/eval.rs
src/lurk/state.rs

* Generalize error message formatting in Lair's Preimg and AssertEq
* Remove the dependency on `lurk` from the `lair` module
* The execution algorithm was calling a bigint formatting function
* Move Lurk specific message formatting to the reduction model
* Implement `fail` with a proper message for good user feedback

feat: `fail` built-in

---

Cargo.lock
Cargo.toml
demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/functional-commitment.lurk
demo/protocol.lurk
lib/util-test.lurk
src/lair/execute.rs
src/lair/mod.rs
src/loam/evaluation.rs
src/lurk/cli/meta.rs
src/lurk/cli/tests/first.lurk
src/lurk/cli/tests/prove.lurk
src/lurk/cli/tests/second.lurk
src/lurk/cli/tests/verify.lurk
src/lurk/eval.rs
src/lurk/eval_tests.rs
src/lurk/tag.rs
src/lurk/zstore.rs

Make it so that `Tag::to_field` doesn't need to skip reserved tags by pushing reserved tags to start from where tags end.

chore: enhance `ReservedTag::to_field`

---

src/lurk/cli/comm_data.rs
src/lurk/cli/lurk_data.rs
src/lurk/cli/meta.rs
src/lurk/cli/proofs.rs
src/lurk/cli/repl.rs
src/lurk/cli/zdag.rs
src/lurk/state.rs

Implement the following meta commands:
* `micro-chain-serve` to start a chain server
* `micro-chain-get` for a client to get the current server state
* `micro-chain-transition` for a client to send a chain proof to the server
This is a minimal implementation for a demo and doesn't assume too much from the actual final micro-chain system, on which we will have more info later.

feat: micro-chain simulator

---

lib/util.lurk
src/lurk/eval.rs
src/lurk/state.rs
src/lurk/tests/eval.rs
src/lurk/tests/lang.rs

This PR adds:
* `apply` builtin: `(apply f args)` will call `f` passing the arguments from the `args` list. For example, `(apply (lambda (x y) (+ x y)) (list 1 2))`
* Support for `&rest` parameters in function definitions, allowing for variadic functions. For example, `(lambda (x &rest y) ...)`
There is some unfortunate code duplication in `apply`, but this solution is better (in terms of columns and code complexity) for now. We might be able to simplify the duplication out in the future.
Manual update: https://github.com/argumentcomputer/user-manual/pull/24

feat: Add support for `&rest` parameters and `apply` as a built-in

---

Cargo.lock
src/lurk/cli/meta.rs
src/lurk/state.rs

Implement an `update` meta command which can update env variables with arbitrary functions.

feat: `update` meta command

---

src/lurk/eval.rs
src/lurk/state.rs
src/lurk/tests/eval.rs

Implement `eqq`, which is similar to `eq` but doesn't evaluate the first argument.

feat: `eqq` built-in

---

demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/functional-commitment.lurk
demo/protocol.lurk
lib/util-test.lurk
lib/util.lurk
src/lurk/cli/meta.rs
src/lurk/cli/tests/first.lurk
src/lurk/cli/tests/prove.lurk
src/lurk/cli/tests/second.lurk
src/lurk/cli/tests/verify.lurk
src/lurk/eval.rs
src/lurk/tag.rs
src/lurk/tests/eval.rs
src/lurk/zstore.rs

Make the bodies of `let`, `letrec` and `lambda` behave as if there were an implicit `begin` wrapping the code after the binding variables.
Important: this patch makes the body of every `Fun` object a `Cons` such that `(lambda (x) x)` actually prints to `<Fun (x) (x)>`.

feat: implicit begin

---

src/lurk/cli/meta.rs
src/lurk/cli/proofs.rs

Make the micro-chain simulator also accept regular functions as callable objects (besides functional commitments, which were already supported).

chore: extend micro-chain simulator callables

---

src/lurk/cli/meta.rs
src/lurk/cli/tests/mod.rs
src/lurk/eval.rs

Remove code that was evaluating transition arguments, as that might turn expressions such as `'(1 2 3)` into `(1 2 3)`, which is not a valid argument for a call.
Extra:
* Remove useless path in `apply` coroutine
* Add a test for the demo files

fix: transitin meta command

---

Cargo.toml

This trick makes loam use an ascent package (including its dependencies, therefore including ascent-derive) that's compiled in release mode, even in debug builds.
Saves a few seconds in my IDE.

fix: speed up ascent

---

demo/mastermind.lurk

This PR fixes a bug (loop detected) in the `maybe-remove` implementation of the mastermind demo and improves the game UX by always specifying which player's guess is expected.

Mastermind fixes

---

src/lurk/cli/comm_data.rs
src/lurk/cli/lurk_data.rs
src/lurk/cli/meta.rs
src/lurk/cli/microchain.rs
src/lurk/cli/mod.rs
src/lurk/cli/proofs.rs
src/lurk/cli/repl.rs
src/lurk/cli/zdag.rs
src/lurk/mod.rs
src/lurk/stark_machine.rs
src/lurk/state.rs
src/lurk/zstore.rs

* Make the server completely passive. Instead of a meta command, it's now done via command line: `lurk microchain <addr>`
* Clients can spawn new microchains and get an ID back
* Clients can retrieve the genesis state by ID
* Clients can fetch the current state by ID
* Clients can provide proofs of state transition by ID
* Clients can verify the entire microchain by ID
Extra:
* Fix old hole in the DAG by memoizing the DAG of the current env before calling `intern_env`

chore: revamp the microchain API

---

src/lurk/cli/config.rs
src/lurk/cli/tests/mod.rs

This fixes a "Config already set" bug that happens sometimes when running the tests

Removed `expect` from `set_config`

---

demo/bank.lurk
demo/chained-functional-commitment.lurk
src/lurk/cli/tests/first.lurk
src/lurk/cli/tests/second.lurk
src/lurk/eval.rs
src/lurk/tests/eval.rs
src/lurk/zstore.rs

There's no need to convert the bindings to an efficient form because we always extend the same environment, so the extension is only done once (the rest is memoized)

No need for `collect_bindings_as_an_env`

---

demo/mini-mastermind.lurk

This PR adds a minimalistic adaptation of the mastermind demo, for simpler comparison with [Veridise's zk Language Comparison](https://github.com/Veridise/zk-language-comparison/tree/main).
It adds a `score-one-turn` function, since the examples in the comparison above only score a single turn.
The only substantive difference is that `code-valid?` considers 0 a valid code, so we can use the same [test](https://github.com/Veridise/zk-language-comparison/blob/c330834280cf680d5daac9eceba1ddd5ec9da2bf/circom/examples/input1.json) [cases](https://github.com/Veridise/zk-language-comparison/blob/c330834280cf680d5daac9eceba1ddd5ec9da2bf/circom/examples/input2.json) as the [Circom baseline implementation](https://github.com/Veridise/zk-language-comparison/tree/main/circom).

Add mini-mastermind demo.

---

benches/fib.rs
benches/lcs.rs
benches/sum.rs
demo/mastermind.lurk
src/loam/allocation.rs
src/loam/distilled_evaluation.rs
src/loam/evaluation.rs
src/lurk/cli/meta.rs
src/lurk/cli/repl.rs
src/lurk/cli/tests/first.lurk
src/lurk/cli/tests/second.lurk
src/lurk/cli/tests/verify.lurk
src/lurk/eval.rs
src/lurk/parser/base.rs
src/lurk/parser/error.rs
src/lurk/parser/mod.rs
src/lurk/parser/string.rs
src/lurk/parser/syntax.rs
src/lurk/state.rs
src/lurk/syntax.rs
src/lurk/tests/eval.rs
src/lurk/tests/lang.rs
src/lurk/zstore.rs
tests/fib.rs

Makes it possible to assemble meta commands in Lurk expressions. Each meta command is resolved to the value it returns before evaluating the whole expression with the VM.
Closes #218

feat: composable meta commands

---

src/lurk/cli/meta.rs
src/lurk/cli/repl.rs
src/lurk/cli/tests/first.lurk
src/lurk/cli/tests/second.lurk
src/lurk/state.rs

* Remove printing side effects that should be handled from outside
* Drop the `fetch` meta command as `open` can do the job

chore: print returns from meta commands

---

src/lurk/cli/zdag.rs
src/lurk/tests/eval_direct.rs
src/lurk/zstore.rs

We're not constructing this kind of data anymore - since `Thunk`s (now `Fix`) were changed.

chore: drop `Tuple100`-related API

---

src/lurk/cli/comm_data.rs
src/lurk/cli/lurk_data.rs
src/lurk/cli/microchain.rs
src/lurk/cli/paths.rs
src/lurk/cli/proofs.rs
src/lurk/cli/zdag.rs

Instead of bloating the server's RAM with data from potentially many microchains, persist the data on the file system. This allows servers to not lose data on temporary shutdowns.

feat: persisting microchain server data

---

demo/bank.lurk
demo/chained-functional-commitment.lurk
demo/functional-commitment.lurk
src/core/cli/meta.rs
src/core/cli/repl.rs
src/core/zstore.rs

`call`, `chain`, `transition` and `microchain-transition` will now evaluate their arguments out of circuit and assemble the call expr to be proved using the evaluated, but quoted, arguments.

chore: change `call`-based meta commands

---

src/core/cli/comm_data.rs
src/core/cli/meta.rs
src/core/cli/repl.rs

The arguments must be the evaluated+quoted ones and the env must be empty.

fix: use correct arguments and env for chain transitions

---

src/core/cli/meta.rs
src/core/cli/microchain.rs
src/core/eval_direct.rs
src/core/state.rs
src/core/tests/eval_compiled.rs
src/core/tests/eval_direct.rs

Implement `env` and `bind` as primitives for env construction.
Extra:
* Adapt the microchain server to send only a slice of the transition proofs, chosen by the client. This is necessary for when the VM changes (as in this patch) and the client would no longer accept old proofs sent by the server. Then the client can reconsider what qualifies as the new genesis and verify proofs from there.

feat: `env` and `bind` built-ins

---

src/core/cli/repl.rs
src/core/eval_direct.rs
src/core/parser/syntax.rs
src/core/syntax.rs
src/core/tests/eval_direct.rs
src/core/zstore.rs

Deals with #408, #409, and #410.
```
(base) ➜  lurk git:(whz/fix-env) ✗ cargo run 
Compiling lurk v0.5.0 (/Users/hantingz/Work/lurklab/lurk)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.46s
Running `target/debug/lurk`
commit: 2025-01-16 db1a1f1c2250f3b17ded488068eac4a1ffd1c2f5
Lurk REPL welcomes you.
lurk-user> {}
[1 iteration] => {  }
lurk-user> { a: 1 }
[2 iterations] => { a: 1 }
lurk-user> { a: 1, b: 2 }
[3 iterations] => { a: 1, b: 2 }
lurk-user> { a: (+ 1 3), b: 2 }
[5 iterations] => { a: 4, b: 2 }
lurk-user> '{ a: (+ 1 3), b: 2 }
[1 iteration] => { a: (+ 1 3), b: 2 }
lurk-user> (eval '(+ a 1) { a: 1 })
[7 iterations] => 2
lurk-user> (eval 'a '{ a: (1 1), b: 2 })
[4 iterations] => (1 1)
lurk-user> (let ((a 1)) (current-env))
[3 iterations] => { a: 1 }
lurk-user> …
```

feat: Add curly brace syntax for env read/eval/print

---

src/core/cli/meta.rs
src/core/cli/mod.rs
src/core/cli/paths.rs
src/core/cli/repl.rs
src/core/cli/tests/mod.rs

This PR adds ability to load LurkScript (`.ls`) files and to read LurkScript at the REPL (if run with `--lurkscript` flag).
Note, this work assumes `lurkscript` has been installed and is in the path.
Loading uses file suffix detection to be minimally intrusive.
TODO:
- make `lurkscript` return distinct error on incomplete input vs other cases
- continue to accumulate input when incomplete, but handle and report other errors
examples:
```
(base) ➜  lurk git:(lurkscript) ✗ lurk load 'lib/foo.ls'
commit: 2025-02-07 a7f39b596a456a80677e04addda69d22b95a8e36
Loading lib/foo.ls
[2 iterations] => 2
(base) ➜  lurk git:(lurkscript) ✗ lurk
commit: 2025-02-07 a7f39b596a456a80677e04addda69d22b95a8e36
Lurk REPL welcomes you.
lurk-user> !(load "lib/foo.ls")
Loading /Users/clwk/fil/lurk/lib/foo.ls
[2 …
```

Lurkscript

---

src/core/cli/repl.rs
src/core/zstore.rs

Changing the default behavior of the parser to create unknown packages for now. The issue is described in this comment: https://github.com/lurk-lab/lurk/issues/422#issuecomment-2657883045
Once we have a better structure around interning symbols from other packages (including possibly unknown packages), this might be changed again in the future.
```
lurk-user> !(def .foo.bar 123) ;; this creates the unknown package `.foo`, by default it's empty
.foo.bar
lurk-user> !(in-package .foo)
.lurk.t
foo> bar
[1 iteration] => 123
foo>
```

fix: Change `create_unknown_packages` default from `false` to `true`

---

src/core/parser/syntax.rs
src/core/tests/eval_direct.rs
src/core/zstore.rs

Fixes #417
Before:
```
lurk-user> (eval 'a { a: 1, b: 2, a: 3 })
[7 iterations] => 1
lurk-user> !(def a 1)
a
lurk-user> !(def a 2)
a
lurk-user> (current-env)
[1 iteration] => { a: 2, a: 1 }
```
After:
```
lurk-user> (eval 'a { a: 1, b: 2, a: 3 })
[7 iterations] => 3
lurk-user> { a: 1, b: 2, a: 3 }
[4 iterations] => { a: 1, b: 2, a: 3 }
lurk-user> !(def a 1)
a
lurk-user> !(def a 2)
a
lurk-user> (current-env)
[1 iteration] => { a: 1, a: 2 }
```

fix: Reverse the printed/parsed order of env bindings internally

---

src/core/eval_direct.rs
src/core/tests/eval_direct.rs

The ordering of bindings inside an Env created between `let` and `letrec` were not matching:
```
lurk-user> (letrec ((a 123) (b 456)) (current-env))
[6 iterations] => { b: <Fix 456>, a: <Fix 123> }
lurk-user> (let ((a 123) (b 456)) (current-env))
[4 iterations] => { a: 123, b: 456 }
lurk-user> (let ((a 1) (a 2)) a)
[4 iterations] => 2
lurk-user> (letrec ((a 1) (a 2)) a)
[6 iterations] => 1
```
This PR fixes this behavior and adds two tests covering this:
```
lurk-user> (letrec ((a 123) (b 456)) (current-env))
[6 iterations] => { a: <Fix 123>, b: <Fix 456> }
lurk-user> (letrec ((a 1) (a 2)) a)
[6 iterations] => 2
```

fix: Reverse ordering of `letrec` binds to match `let`

---

lib/struct.ls
lib/struct.lurk
lib/util-test.ls
lib/util-test.lurk
lib/util.ls
src/core/cli/tests/mod.rs

This PR add a test to run `lib/tests.ls` with `lurkscript`. It also contains a few small clean-up items discovered while ensuring `lurkscript` the new test will pass.

lib tests with standalone lurkscript
